version: "3.8"

services:
    api:
        build: .
        ports:
            - 8000:8000
        environment:
            - DB_URL=mongodb://database/TodoList
        volumes:
            - ./app:/app
    db:
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - taskdb:/data/database
volumes:
    taskdb:



